### ISSUE TITLE
Error when table contains json field

### ISSUE THREAD

**Issue by AndreyMai** [PGHist/PGHist#1]
select * from zvs_changes()

gets an error:

SQL Error [42883]: ERROR: operator does not exist: json <> json
  Подсказка: No operator matches the given name and argument types. You might need to add explicit type casts.
  Где: PL/pgSQL function zvs_changes(text,anyelement,text,boolean) line 88 at IF

**Comment by PGHist** [comment]
Thanks for feedback, bug fixed
